apiVersion: v1
kind: Service
metadata:
  name: nginx-workshop-service
  labels:
    app: nginx-workshop 
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-workshop
  sessionAffinity: None
